In [ ]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
from io import StringIO

url = "https://en.wikipedia.org/wiki/List_of_largest_companies_by_revenue"
headers = {"User-Agent": "MyProject/1.0 (binii@example.com)"}

page = requests.get(url, headers=headers)
soup = BeautifulSoup(page.text, 'html.parser')

In [ ]:
tables = pd.read_html(StringIO(str(soup)))
print(len(tables))  # see how many tables found
df = tables[0]

6

In [ ]:
df.to_csv("largest_company.csv", index=False)
print("saved!")

saved!

In [ ]:
import os
os.getcwd()  # shows you where it saved

'/content'

In [ ]:
from google.colab import files
files.download("largest_company.csv")

In [ ]:
df=pd.read_csv("largest_company.csv")
df.head()

,Ranks,Name,Industry,Revenue,Profit,Employees,Headquarters[note 1],State-owned,Ref.
0,Ranks,Name,Industry,USD (in billions),USD (in billions),Employees,Headquarters[note 1],State-owned,Ref.
1,1,Amazon,Retail Information technology,716,79.9,1576000,United States,NaN,[5]
2,2,Walmart,Retail,713,21.8,2100000,United States,NaN,[6]
3,3,State Grid Corporation of China,Electricity,545,9.2,1361423,China,NaN,[7]
4,4,Saudi Aramco,Oil and gas,480,106.0,73311,Saudi Arabia,NaN,[8]

In [ ]:
df = df.iloc[1:].reset_index(drop=True)  # clean
df.to_csv("largest_companies.csv", index=False)  # overwrite the old csv
print("saved!")

saved!

In [ ]:
df.head()

,Ranks,Name,Industry,Revenue,Profit,Employees,Headquarters[note 1],State-owned,Ref.
0,1,Amazon,Retail Information technology,716,79.9,1576000,United States,NaN,[5]
1,2,Walmart,Retail,713,21.8,2100000,United States,NaN,[6]
2,3,State Grid Corporation of China,Electricity,545,9.2,1361423,China,NaN,[7]
3,4,Saudi Aramco,Oil and gas,480,106.0,73311,Saudi Arabia,NaN,[8]
4,5,China National Petroleum Corporation,Oil and gas,476,25.2,1026301,China,NaN,[9]